routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    Route::get('/', 'HomeController@index')->name('home');

    Route::prefix('{id}')->name('courses.')->group( function() {
        Route::get('/', 'CourseController@index')->name('index');

        Route::get('evalue', 'EvalueController@index')->name('get_evalue');
        Route::post('evalue', 'EvalueDataController@evalue')->name('post_evalue');

        Route::get('export', 'ExportDataController@index')->name('get_export');
        Route::post('export', 'ExportDataController@export')->name('post_export');

        Route::get('train', 'TrainController@index')->name('get_train');
        Route::post('train', 'TrainController@training')->name('post_train');

        Route::get('predict', 'ExportDataController@index')->name('get_predict');
        Route::post('predict', 'ExportDataController@export')->name('post_predict');
    });

resources/views/course_index.blade.php
@extends('layouts.master1')

@section('title', 'Course detail')

@section('content')

<div class="container">
    <div class="card bg-light mt-3">
      @if (Session::has('message'))
        {{ session()->get('message') }}
      @endif
      <form action="{{ route('courses.post_export', '$id') }}" method="POST">
          <div class="card-header">
            @csrf
            Export data from data base to train
          </div>
          <div class="card-body">
            <button type="submit" class="btn btn-warning">
              Export Data
            </button>
          </div>
      </form>
    </div>
</div>
@endsection

resources/views/evalue.blade.php
@extends('layouts.master1')

@section('title', 'Course detail')

@section('content')

<div class="container">
    <div class="card bg-light mt-3">
      @if (Session::has('message'))
        {{ session()->get('message') }}
      @endif
      <form action="{{ route('courses.post_evalue', '$id') }}" method="POST">
          <div class="card-header">
            @csrf
            Tính toán trình độ của học sinh
          </div>
          <div class="card-body">
            <button type="submit" class="btn btn-warning">
              Tính toán 
            </button>
          </div>
      </form>
    </div>
</div>
<br/>
<hr/>

<div class="container">
	<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="row">#</th>
      <th scope="col">User</th>
      <th scope="col">Lesson</th>
      <th scope="col">Level of student</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"></th>
      
    </tr>
  </tbody>
</table>
</div>
@endsection

resources/views/export.blade.php
@extends('layouts.master1')

@section('title', 'Course detail')

@section('content')

<div class="container">
    <div class="card bg-light mt-3">
      @if (Session::has('message'))
        {{ session()->get('message') }}
      @endif
      <form action="{{ route('courses.post_export', '$id') }}" method="POST">
          <div class="card-header">
            @csrf
            Export new data from database
          </div>
          <div class="card-body">
            <button type="submit" class="btn btn-warning">
              Export Data
            </button>
          </div>
      </form>
    </div>
</div>
<br/>
<hr/>

<div class="container">
	<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="row">#</th>
      <th scope="col">User</th>
      <th scope="col">Lesson</th>
      <th scope="col">Level of student</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($datas as $data)
    <tr>
      <th scope="row"></th>
      <td>{{$data->user_id}}</td>
      <td>{{$data->section}}</td>
      <td>{{$data->level}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
{{ $datas->links() }}
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('title', 'Course detail')

@section('content')

@endsection

resources/views/train.blade.php
@extends('layouts.master1')

@section('title', 'Course detail')

@section('content')
  <div class="col-md-8 course-main">
        <div id="message" class="">
          
        </div>
        <h1 class="border-bottom">
          Huấn luyện mô hình
        </h1>
        <form>
          @csrf
          <label for="sel1"><b>Tham số dùng cho giải thuật</b></label>
          <div class="row form-group">
              <label class="control-label col-md-3" for="subcategory_id">Number factor K</label>
              <input class="form-control col-md-2" type="number" value="0" id="example-number-input"
              min=0 max=1000 step=1 name="number_factor" required>
              <label  class="control-label col-md-2" for="type_id">Max n_epochs</label>
              <input class="form-control col-md-2" type="number" value="0" id="example-number-input"
              min=0 max=1000 step=1 name="epoch" required>
          </div>  
          <div class="row form-group">
              <label class="control-label col-md-3" for="subcategory_id">Learning rate</label>
              <input class="form-control col-md-2" type="number" value="0" id="example-number-input"
                min=0 max=1 step=0.001 name="learning_rate" required>
              <label  class="control-label col-md-2" for="type_id">Regularization</label>
              <input class="form-control col-md-2" type="number" value="0" id="example-number-input"
                min=0 max=1 step=0.005 name="regular" required> 
          </div>  
          <div>
            <button type="button" class="btn btn-info" id="submit">Dự đoán</button>
          </div>
        </form>
        </div><!-- /.course-post -->
    @include('partials.sidebar')
@endsection
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
  $(document).ready(function () {
    $.ajaxSetup({
                  headers: {
                      'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                  }
              });
    $("#submit").click(function(e){
        e.preventDefault();
        var number_factor= $("input[name=number_factor]").val();
        var epoch = $("input[name=epoch]").val();
        var learning_rate = $("input[name=learning_rate]").val();
        var regular = $("input[name=regular]").val();
        $.ajax({
           type:'POST',
           url:"{{route('courses.post_train', $id)}}",
           dataType: 'json',
           data:{
              number_factor:number_factor, 
              epoch:epoch, 
              learning_rate:learning_rate,
              regular:regular,
              _token: '{{csrf_token()}}'
            },
           success:function(data){
              if(data["excute_time"]) {
                var message = $("#message");
                message.html("");
                message.removeClass('alert alert-danger');

                var mrse = $("#rmse");
                var execute = $("#execute");
                
                mrse.val(data["rmse"]);
                execute.val(data["excute_time"]);

              } else if(data.message) {
                var message = $("#message");
                message.html("");
                message.addClass('alert alert-danger');
                message.append(data.message);
              }
            }
        });
    });
  });
</script>