routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    Route::get('/', 'HomeController@index')->name('home');

    Route::prefix('{id}')->name('courses.')->group( function() {
        Route::get('/', 'CourseController@index')->name('index');

        Route::get('evalue', 'EvalueController@index')->name('get_evalue');
        Route::post('evalue', 'EvalueDataController@evalue')->name('post_evalue');

        Route::get('export', 'ExportDataController@index')->name('get_export');
        Route::post('export', 'ExportDataController@export')->name('post_export');

        Route::get('train', 'TrainController@index')->name('get_train');
        Route::post('train', 'TrainController@training')->name('post_train');

        Route::get('predict', 'ExportDataController@index')->name('get_predict');
        Route::post('predict', 'ExportDataController@export')->name('post_predict');
    });

resources/views/partials/banner.blade.php
<div class="banner p-3 p-md-5 text-white rounded">
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">Học, học nữa, học mãi</h1>
        <p class="lead my-3">Trường học có thể hô biến những người thắng và người bại, nhưng cuộc sống thì không – Bill Gate –</p>
        <hr/>
        <p class="lead my-3">Giáo dục là vũ khí mạnh nhất mà người ta có thể sử dụng để thay đổi cả thế giới.
		– N. Mandela –</p>
		<hr/>
		<p class="lead my-3">Muốn xây dựng đất nước, trước hết phải phát triển giáo dục. Muốn trị nước phải trọng dụng người tài – Chiếu Lập Học –</p>
        <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
</div>

resources/views/partials/footer.blade.php
<footer class="course-footer">
    <p>Course template built for <a href="https://getbootstrap.com/">ĐATN</a> by Nguyễn Quốc Lâm</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

resources/views/partials/header.blade.php
<header class="course-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <a class="text-muted" href="#"></a>
        </div>
        <div class="col-4 text-center">
            <a class="course-header-logo text-dark" href="#">Chương trình thử nghiệm</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              	<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#"></a>
        </div>
    </div>
</header>

resources/views/partials/menu.blade.php
<nav class="course-nav navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-3 mt-lg-0 nav-pills nav-fill">
      <li class="nav-item active">
        <a class="nav-link" href="{{route('home')}}">Trang chủ</a>
      </li>
      <li class="nav-item dropdown">
	    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Khoá học</a>
	    <div class="dropdown-menu">
	      <a class="dropdown-item" href="{{route('courses.index', '12')}}">Khoá học toán 3</a>
	      <a class="dropdown-item" href="{{route('courses.index', '12')}}">Khoá học toán 4</a>
	      <a class="dropdown-item" href="{{route('courses.index', '12')}}">Khoá học toán 5</a>
	      <div class="dropdown-divider"></div>
	    </div>
    </ul>
   <!--  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

resources/views/partials/menu1.blade.php
<nav class="course-nav navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-3 mt-lg-0 nav-pills nav-fill">
      <li class="nav-item active">
        <a class="nav-link" href="{{route('home')}}">Trang chủ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('courses.get_evalue', $id)}}">Đánh giá trình độ học sinh</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('courses.get_export', $id)}}">Export dữ liệu</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('courses.get_train', $id)}}">Huấn luyện</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('courses.get_predict', $id)}}">Dự đoán</a>
      </li>
    </ul>
   <!--  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

resources/views/partials/recommend.blade.php
<aside class="course-recommend col-md-4">
          <div class="p-3 mb-3 bg-light rounded">
            <h3 class="font-italic">Gợi ý cho bạn</h3>
            <ol class="list-unstyled mb-0">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
        </aside>

resources/views/partials/sidebar.blade.php
<aside class="course-sidebar col-md-4">
            <div class="card">
              <div class="card-header" >
                <h3 class="">Kết quả thử nghiệm</h3>
              </div>
                    
              <div id="" class="collapse show" aria-labelledby="" data-parent="#accordion">
                <div class="row form-group">
                  <label class="control-label col-md-4" for="subcategory_id">RMSE</label>
                  <input class="form-control col-md-6" type="text" value="0" disabled id="rmse">
                </div>  
                <div class="row form-group">
                  <label class="control-label col-md-4" for="subcategory_id">Time Test</label>
                  <input class="form-control col-md-6" type="text" value="0" disabled id="execute">
                </div>  
              </div>
            </div>
        </aside>

resources/views/partials/sidebar1.blade.php
<aside class="course-sidebar col-md-4">
            <div class="card">
              <div class="card-header" >
                <h3 class="">Kết quả thử nghiệm</h3>
              </div>
                    
              <div id="" class="collapse show" aria-labelledby="" data-parent="#accordion">
                <div class="row form-group">
                  <label class="control-label col-md-4" for="subcategory_id">Danh sách gợi ý</label>
                  <input class="form-control col-md-6" type="text" value="0" disabled>
                </div>  
                <div class="row form-group">
                  <label class="control-label col-md-4" for="subcategory_id">Time Test</label>
                  <input class="form-control col-md-6" type="text" value="0" disabled>
                </div>  
              </div>
            </div>
        </aside>